app:
  eureka-username: u
  eureka-password: p

# eureka:
#   instance:
#     hostname: localhost
#   client:
#     registerWithEureka: false
#     fetchRegistry: false
#     serviceUrl:
#       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#   server:
#     waitTimeInMsWhenSyncEmpty: 0
#     response-cache-update-interval-ms: 5000

# app.config-server: config-server
