apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edge-ngrok
  annotations:
    # certmanager.k8s.io/issuer: "letsencrypt-issuer-staging"
    certmanager.k8s.io/issuer: "letsencrypt-issuer-prod"
spec:
  tls:
  - hosts:
    - 6797-174-249-83-34.ngrok.io
    secretName: tls-ngrok-letsencrypt-certificate
  rules:
  - host: 6797-174-249-83-34.ngrok.io
    http:
      paths:
      - path: /oauth
        pathType: Prefix
        backend:
          service: 
            name: auth-server
            port:
              number: 80
      - path: /product-composite
        pathType: Prefix
        backend:
          service:
            name: product-composite
            port: 
              number: 80
      - path: /actuator/health
        pathType: Prefix
        backend:
          service: 
            name: product-composite
            port:
              number: 80